[Board Config]
Vector Generator Type = "None"
VGGO Addr = "0x0"
VGRST Addr = "0x0"
HALT addr = "0x0"
HALT bit = "0x0"
VG Ram addr = "0x0"
VG Ram Size = "0x0"
Mathbox Type = "None"
Mathbox Base Addr = "0x0"
# of Pokeys = 0
Pokey1 Addr = "0x0"
Pokey2 Addr = "0x6000"
Pokey3 Addr = "0x0"
Pokey4 Addr = "0x0"
Pokey Split Offset = "0x0"
Watchdog Addr = "0x0"
MO Object = "0x0"
MO Color = "0x0"
MO Color Ram = "0x0"
MO Vert = "0x0"
MO Horiz = "0x0"
Idle Address = "0x0"
PF RAM Start = "0x0"
PF Color RAM = "0x0"
PF RAM End = "0x0"
Watchdog Data = "0x0"
CPU Type = "Z80"
MO Increment = "0x1"
Clk Freq (MHz) = 1.000000
Use IOREQ for I/O  = FALSE

[EAROM Config]
EAROM Addr_Data = "0x0"
EAROM control = "0x0"
EAROM read = "0x0"
EAROM CS1bit = "0x0"
EAROM C2bit = "0x0"
EAROM C1nbit = "0x0"
EAROM CKbit = "0x0"

[Paths]
RomPath = "."

[ROM]
RomVerToTest = "6/17"

[RomRegion1]
Start = "0x0"
End = "0x1FFF"
Location = "D2"
FileName = "tron\\pro0.d2"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x4278"
9010a signature = "0x581A"
CRC32 = "0xDE0471A"
SHA-1 = "378847604a6a9c079d887348010ab9539d5f6195"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "8/9"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "AH78,0634,A06A,C54C,1528,AC12,99HU,7AF0"
ROM Type = "2764"
Options = ""

[RomRegion2]
Start = "0x0"
End = "0x1FFF"
Location = "D2"
FileName = "tron4\\pga-615.d2"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x3809"
9010a signature = "0xFC43"
CRC32 = "0x9D7A95A"
SHA-1 = "630f4c43204df0510926c5fc07e0c1b3783cf5e4"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/15"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "18CP,0UPF,9C28,43A0,FPA1,8C66,C3FA,239P"
ROM Type = "2764"
Options = ""

[RomRegion3]
Start = "0x0"
End = "0x1FFF"
Location = "D2"
FileName = "tron2\\scpu_pga.d2"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x3178"
9010a signature = "0xA121"
CRC32 = "0x5151770B"
SHA-1 = "26f4d830de7be228528e462dd628f439629a2641"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/25"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "PP90,AC7C,2F7U,C503,7UA6,7833,5F45,12P8"
ROM Type = "2764"
Options = ""

[RomRegion4]
Start = "0x0"
End = "0x1FFF"
Location = "D2"
FileName = "tron3\\scpu_pga.d2"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x378B"
9010a signature = "0xA3CF"
CRC32 = "0xFC33AFD7"
SHA-1 = "99a2ed972c3db477f35a7162079563367864f207"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/17"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "18CP,0UPF,9115,U234,57C4,0F8H,85C5,239P"
ROM Type = "2764"
Options = ""

[RomRegion5]
Start = "0x2000"
End = "0x3FFF"
Location = "D3"
FileName = "tron\\scpu_pgb.d3"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x32DC"
9010a signature = "0x8A9B"
CRC32 = "0x8DDF8717"
SHA-1 = "e0c294afa8ba0b0ba89e3e0fb3ff6d8fc4398e32"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/25, 8/9"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "33FF,U2H1,CC93,9275,2C0C,05FU,A9P1,747P"
ROM Type = "2764"
Options = ""

[RomRegion6]
Start = "0x2000"
End = "0x3FFF"
Location = "D3"
FileName = "tron4\\pgb-615.d3"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x1DB9"
9010a signature = "0x1D55"
CRC32 = "0xB454337D"
SHA-1 = "c2306ad5401a3f60e231be59198610a36b527f1f"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/15"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "33F0,AFUP,03F8,19P3,A445,A972,1C32,220F"
ROM Type = "2764"
Options = ""

[RomRegion7]
Start = "0x2000"
End = "0x3FFF"
Location = "D3"
FileName = "tron3\\scpu_pgb.d3"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x1F77"
9010a signature = "0xFDB5"
CRC32 = "0x7D9E22AC"
SHA-1 = "16a6e9651d5f764e8762fd8d6e53d13fda7473de"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/17"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "1263,7F6P,F43H,8030,709C,48PA,P040,FF77"
ROM Type = "2764"
Options = ""

[RomRegion8]
Start = "0x4000"
End = "0x5FFF"
Location = "D4"
FileName = "tron\\scpu_pgc.d4"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xBCDD"
9010a signature = "0xC42A"
CRC32 = "0x4241E3A0"
SHA-1 = "24c1bd2f31e194542571c391c5dccf21354115c2"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/25, 8/9"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "A41U,0FCF,6U8U,U415,UA88,5054,73F0,U9C6"
ROM Type = "2764"
Options = ""

[RomRegion9]
Start = "0x4000"
End = "0x5FFF"
Location = "D4"
FileName = "tron4\\pgc-615.d4"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xE51A"
9010a signature = "0x134C"
CRC32 = "0xAC1836FF"
SHA-1 = "a8d20facf91b4c93082f8e71a663e5da8b036ecb"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/15"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "44AC,6AHF,0466,HH60,FH87,4CHH,5030,2A2U"
ROM Type = "2764"
Options = ""

[RomRegion10]
Start = "0x4000"
End = "0x5FFF"
Location = "D4"
FileName = "tron3\\scpu_pgc.d4"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xE577"
9010a signature = "0x677E"
CRC32 = "0x902011C6"
SHA-1 = "17ac768a0fd1278ae83414f0d67d6ac8337f4773"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/17"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "5908,P54U,F0U5,1C90,8890,39P3,2P8F,2PHP"
ROM Type = "2764"
Options = ""

[RomRegion11]
Start = "0x6000"
End = "0x7FFF"
Location = "D5"
FileName = "tron\\scpu_pgd.d5"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xCB19"
9010a signature = "0xB712"
CRC32 = "0x35D2FE7"
SHA-1 = "1b827ca30a439d2f4cc94fcc0e90ee0cf87e018c"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/25, 8/9"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "75PF,U9A6,587F,CFF5,U966,9695,5F22,P407"
ROM Type = "2764"
Options = ""

[RomRegion12]
Start = "0x6000"
End = "0x7FFF"
Location = "D5"
FileName = "tron4\\pgd-615.d5"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xBBE2"
9010a signature = "0xB7B7"
CRC32 = "0x1A7BEC6D"
SHA-1 = "4d47020494e0963db22473a459e97c1c06c4b5ee"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/15"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "879F,H011,A5U4,7705,86F8,F2CH,PF5F,257H"
ROM Type = "2764"
Options = ""

[RomRegion13]
Start = "0x6000"
End = "0x7FFF"
Location = "D5"
FileName = "tron3\\scpu_pgd.d5"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xB9D3"
9010a signature = "0xC890"
CRC32 = "0x86477E89"
SHA-1 = "196f0d3930d10bfe4ddee82ce8b28bb99324069e"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/17"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "A7PA,5UC2,F00F,8174,PHFF,7C8U,4UA2,AH19"
ROM Type = "2764"
Options = ""

[RomRegion14]
Start = "0x8000"
End = "0x9FFF"
Location = "D6"
FileName = "tron\\scpu_pge.d6"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xCD51"
9010a signature = "0xF601"
CRC32 = "0x24C185D8"
SHA-1 = "45ac7c53f6f4eba5c7bf3fc6559cddd3821eddad"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/25, 8/9"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "0891,AUUP,6880,FAA3,H134,6120,8C60,C909"
ROM Type = "2764"
Options = ""

[RomRegion15]
Start = "0x8000"
End = "0x9FFF"
Location = "D6"
FileName = "tron4\\pge-615.d6"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xBFDC"
9010a signature = "0xDAF2"
CRC32 = "0xEA198FA8"
SHA-1 = "d8c97ea87d504e77edc38c87c2953c8c4f1a405b"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/15"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "C85A,F5P2,6495,100U,097U,07FC,445A,P97P"
ROM Type = "2764"
Options = ""

[RomRegion16]
Start = "0x8000"
End = "0x9FFF"
Location = "D6"
FileName = "tron3\\scpu_pge.d6"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0xBFDC"
9010a signature = "0xDAF2"
CRC32 = "0xEA198FA8"
SHA-1 = "d8c97ea87d504e77edc38c87c2953c8c4f1a405b"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/17"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "C85A,F5P2,6495,100U,097U,07FC,445A,P97P"
ROM Type = "2764"
Options = ""

[RomRegion17]
Start = "0xA000"
End = "0xBFFF"
Location = "D7"
FileName = "tron\\scpu_pgf.d7"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x3007"
9010a signature = "0xAC54"
CRC32 = "0x38C4BBAF"
SHA-1 = "a7cd496ce75199b8279ea963520cf70d5f562bb2"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/25, 8/9"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "4U90,0UC5,1A1P,70H2,H361,29F0,9C0P,4567"
ROM Type = "2764"
Options = ""

[RomRegion18]
Start = "0xA000"
End = "0xBFFF"
Location = "D7"
FileName = "tron4\\pgf-615.d7"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x2A9"
9010a signature = "0x7ABA"
CRC32 = "0x790EE743"
SHA-1 = "14dc84b2bbaab22772e0579f11fe0bf136a0ddab"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/15"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "H2H9,24F2,1H1P,FA2H,U522,0CCP,0699,C170"
ROM Type = "2764"
Options = ""

[RomRegion19]
Start = "0xA000"
End = "0xBFFF"
Location = "D7"
FileName = "tron3\\scpu_pgf.d7"
Page Reg = "0x0"
Page Bit 0-7 = 0
CAT checksum = "0x337"
9010a signature = "0xEEC9"
CRC32 = "0x4325FB08"
SHA-1 = "70727aa37354425315d8a8b3ca07bbe91f7e8f08"
CAT checksum 2 = "0x0"
9010a signature 2 = "0x0"
Used in Version(s) = "6/17"
EnableAddress = ""
DisableAddress = ""
EnableData = ""
DisableData = ""
Enable Before Test = FALSE
Disable After Test = FALSE
Data Signatures = "FHA6,9PA5,4CU7,2042,F9F2,375P,19P6,P799"
ROM Type = "2764"
Options = ""

[RamRegion1]
Start = "0xC000"
End = "0xC7FF"
Locations High to Low = "B2 - CPU  6116-LP"
EnableAddress = "0x0"
DisableAddress = "0x0"
EnableData = "0x0"
DisableData = "0x0"
Enable Before Test = FALSE
Disable After Test = FALSE
Width = "0x8"
Options = ""

[RamRegion2]
Start = "0xE000"
End = "0xE1FF"
Locations High to Low = "Sprite ram on video board"
EnableAddress = "0x0"
DisableAddress = "0x0"
EnableData = "0x0"
DisableData = "0x0"
Enable Before Test = FALSE
Disable After Test = FALSE
Width = "0x8"
Options = ""

[RamRegion3]
Start = "0xE800"
End = "0xEFFF"
Locations High to Low = "F6 - 6116 Background video"
EnableAddress = "0x0"
DisableAddress = "0x0"
EnableData = "0x0"
DisableData = "0x0"
Enable Before Test = FALSE
Disable After Test = FALSE
Width = "0x8"
Options = ""

[RamRegion4]
Start = "0xFF80"
End = "0xFFBF"
Locations High to Low = "Pallet ram 9bits "
EnableAddress = "0x0"
DisableAddress = "0x0"
EnableData = "0x0"
DisableData = "0x0"
Enable Before Test = FALSE
Disable After Test = FALSE
Width = "0x8"
Options = ""
[INIT SEQUENCE]


[NOTES]

4 Ram sections?





